### PR TITLE
Update README for testing a new release.

### PR DESCRIPTION
**Pull request by rytaft**
Update README with more specific instructions about forking the
repo and making a PR for testing a new release.

### CODE REVIEW

**Comment by rytaft** [comment]
Oh! In that case I'll update it to say use the pencil. I saw that everyone who made the last few changes had done it with a separate fork, so I thought I had done it wrong when I used the pencil.

**Comment by rytaft** [comment]
Updated, PTAL

**Comment by benesch** [comment]
No, not at all! The branches don't really matter here; it's all a rather huge hack to get Travis CI/Appveyor to work.

Anyway, thanks and LGTM!

**Comment by rytaft** [comment]
Thanks!

**Pull request merged**
