### PR TITLE
v1.1.3

### PR DESCRIPTION
**Pull request by mberhault**
https://github.com/cockroachdb/cockroach/issues/20176

### CODE REVIEW

**Comment by mberhault** [comment]
@benesch: the hooks don't seem to be responding.

**Comment by tschottdorf** [comment]
@mberhault I think that's because @benesch very recently moved this repository into `cockroachdb`. I'll see if I can enable travis here.

**Comment by tschottdorf** [comment]
Looks like you're green, actually: https://travis-ci.org/cockroachdb/bincheck

**Comment by tschottdorf** [comment]
Disabled the  status check for now (actually, I tried to re-enable them but they disappeared, I think @benesch just has to set them up again).

Appveyor hasn't run (I think), but that seems.. acceptable.

**Pull request merged**
